version: "3.9"

services:
    mariadb:
        build: requirements/mariadb
        image: mariadb
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mdb_data:/var/lib/mysql
        networks:
            - inception
        restart: unless-stopped
    wordpress:
        build: requirements/wordpress
        image: wordpress
        volumes:
            - wp_data:/www/wordpress
        depends_on:
            - mariadb
        env_file:
            - .env
        environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - inception
        restart: unless-stopped
                            
    nginx:
        build: requirements/nginx
        image: nginx
        depends_on:
            - wordpress
        volumes:
            - wp_data:/www/wordpress
        ports:
            - 443:443
        networks:
            - inception
        restart: unless-stopped

volumes:
    wp_data:
        driver: 'local'
        driver_opts:
            type: 'none'
            device: '/home/elahyani/data/wordpress'
            o: 'bind'
            
    mdb_data:
        driver: 'local'
        driver_opts:
            type: 'none'
            device: '/home/elahyani/data/mariadb'
            o: 'bind'

networks:
    inception: