version: "3.9"

services:
    mariadb:
        build:
            context: requirements/mariadb
            args:
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        image: mariadb
        container_name: mariadb
        env_file:
            - .env
        volumes:
            - mdb_data:/var/lib/mysql
        networks:
            - inception
        restart: unless-stopped
    wordpress:
        build: requirements/wordpress
        image: wordpress
        container_name: wordpress
        volumes:
            - wp_data:/www/wordpress
        depends_on:
            - mariadb
        env_file:
            - .env
        networks:
            - inception
        restart: unless-stopped
    redis:
        build: requirements/bonus/redis
        image: redis
        container_name: redis
        depends_on: 
            - wordpress
        ports: 
            - 6379:6379
        volumes:
            - wp_data:/www/wordpress
        networks: 
            - inception
        restart: unless-stopped
    ftp:
        build: requirements/bonus/ftp
        image: ftp
        container_name: ftp
        depends_on: 
            - wordpress
        ports: 
            - 21:21
            - 10100:10100
        volumes:
            - wp_data:/www/wordpress
        networks: 
            - inception
        restart: unless-stopped
    adminer:
        build: requirements/bonus/adminer
        image: adminer
        container_name: adminer
        ports: 
            - 5000:5000
        networks:
            - inception
        restart: unless-stopped
    nginx:
        build: requirements/nginx
        image: nginx
        container_name: nginx
        depends_on:
            - wordpress
        volumes:
            - wp_data:/www/wordpress
        ports:
            - 443:443
        networks:
            - inception
        restart: unless-stopped

volumes:
    wp_data:
        driver: 'local'
        driver_opts:
            type: 'none'
            device: '/home/elahyani/data/wordpress'
            o: 'bind'
            
    mdb_data:
        driver: 'local'
        driver_opts:
            type: 'none'
            device: '/home/elahyani/data/mariadb'
            o: 'bind'

networks:
    inception: